CXX = g++
CXXFLAGS = -O3 -pthread

assignment_2_par_grppi: assignment_2_par_grppi.cpp
	g++ -std=c++17 -O3 -I /usr/local/include/grppi -pthread assignment_2_par_grppi.cpp -o assignment_2_par_grppi -fconcepts -fconcepts-ts -fpermissive